# Form implementation generated from reading ui file 'pyqt_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 596)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 60, 165, 174))
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.chapter_spin_box = QtWidgets.QSpinBox(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chapter_spin_box.setFont(font)
        self.chapter_spin_box.setObjectName("chapter_spin_box")
        self.gridLayout.addWidget(self.chapter_spin_box, 0, 1, 1, 1)
        self.objective_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.objective_label.setFont(font)
        self.objective_label.setObjectName("objective_label")
        self.gridLayout.addWidget(self.objective_label, 1, 0, 1, 1)
        self.section_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.section_label.setFont(font)
        self.section_label.setObjectName("section_label")
        self.gridLayout.addWidget(self.section_label, 2, 0, 1, 1)
        self.chapter_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.chapter_label.setFont(font)
        self.chapter_label.setObjectName("chapter_label")
        self.gridLayout.addWidget(self.chapter_label, 0, 0, 1, 1)
        self.section_spin_box = QtWidgets.QSpinBox(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.section_spin_box.setFont(font)
        self.section_spin_box.setMaximum(9)
        self.section_spin_box.setSingleStep(1)
        self.section_spin_box.setObjectName("section_spin_box")
        self.gridLayout.addWidget(self.section_spin_box, 2, 1, 1, 1)
        self.objective_spin_box = QtWidgets.QSpinBox(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.objective_spin_box.setFont(font)
        self.objective_spin_box.setObjectName("objective_spin_box")
        self.gridLayout.addWidget(self.objective_spin_box, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(180, 40, 861, 511))
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame1 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame1.setObjectName("frame1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prev_card_btn = QtWidgets.QPushButton(parent=self.frame1)
        self.prev_card_btn.setObjectName("prev_card_btn")
        self.horizontalLayout.addWidget(self.prev_card_btn)
        self.next_card_btn = QtWidgets.QPushButton(parent=self.frame1)
        self.next_card_btn.setObjectName("next_card_btn")
        self.horizontalLayout.addWidget(self.next_card_btn)
        self.show_details_btn = QtWidgets.QPushButton(parent=self.frame1)
        self.show_details_btn.setObjectName("show_details_btn")
        self.horizontalLayout.addWidget(self.show_details_btn)
        self.gridLayout_2.addWidget(self.frame1, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.key_points_textbox = QtWidgets.QTextBrowser(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_points_textbox.sizePolicy().hasHeightForWidth())
        self.key_points_textbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.key_points_textbox.setFont(font)
        self.key_points_textbox.setObjectName("key_points_textbox")
        self.horizontalLayout_2.addWidget(self.key_points_textbox)
        self.details_textbox = QtWidgets.QTextBrowser(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_textbox.sizePolicy().hasHeightForWidth())
        self.details_textbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.details_textbox.setFont(font)
        self.details_textbox.setObjectName("details_textbox")
        self.horizontalLayout_2.addWidget(self.details_textbox)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.card_progress_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.card_progress_label.setGeometry(QtCore.QRect(540, 0, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.card_progress_label.setFont(font)
        self.card_progress_label.setObjectName("card_progress_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.objective_label.setText(_translate("MainWindow", "OBJECTIVE"))
        self.section_label.setText(_translate("MainWindow", "SECTION"))
        self.chapter_label.setText(_translate("MainWindow", "CHAPTER"))
        self.prev_card_btn.setText(_translate("MainWindow", "Previous Card"))
        self.next_card_btn.setText(_translate("MainWindow", "Next Card"))
        self.show_details_btn.setText(_translate("MainWindow", "Show Details"))
        self.key_points_textbox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.details_textbox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.card_progress_label.setText(_translate("MainWindow", "CARD 0/0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
