# Form implementation generated from reading ui file 'quiz_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.card_info_textbox = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.card_info_textbox.setGeometry(QtCore.QRect(270, 110, 281, 192))
        self.card_info_textbox.setObjectName("card_info_textbox")
        self.chapter_spin_box = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.chapter_spin_box.setGeometry(QtCore.QRect(180, 110, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chapter_spin_box.setFont(font)
        self.chapter_spin_box.setObjectName("chapter_spin_box")
        self.objective_spin_box = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.objective_spin_box.setGeometry(QtCore.QRect(180, 160, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.objective_spin_box.setFont(font)
        self.objective_spin_box.setObjectName("objective_spin_box")
        self.section_spin_box = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.section_spin_box.setGeometry(QtCore.QRect(180, 210, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.section_spin_box.setFont(font)
        self.section_spin_box.setMaximum(9)
        self.section_spin_box.setSingleStep(1)
        self.section_spin_box.setObjectName("section_spin_box")
        self.prev_card_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.prev_card_btn.setGeometry(QtCore.QRect(280, 310, 81, 24))
        self.prev_card_btn.setObjectName("prev_card_btn")
        self.flip_card_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.flip_card_btn.setGeometry(QtCore.QRect(380, 310, 75, 24))
        self.flip_card_btn.setObjectName("flip_card_btn")
        self.next_card_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.next_card_btn.setGeometry(QtCore.QRect(470, 310, 75, 24))
        self.next_card_btn.setObjectName("next_card_btn")
        self.chapter_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.chapter_label.setGeometry(QtCore.QRect(80, 110, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chapter_label.setFont(font)
        self.chapter_label.setObjectName("chapter_label")
        self.objective_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.objective_label.setGeometry(QtCore.QRect(80, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.objective_label.setFont(font)
        self.objective_label.setObjectName("objective_label")
        self.section_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.section_label.setGeometry(QtCore.QRect(80, 200, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.section_label.setFont(font)
        self.section_label.setObjectName("section_label")
        self.update_deck_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.update_deck_btn.setGeometry(QtCore.QRect(110, 250, 81, 24))
        self.update_deck_btn.setObjectName("update_deck_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.card_info_textbox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">View Card Information</p></body></html>"))
        self.prev_card_btn.setText(_translate("MainWindow", "Previous Card"))
        self.flip_card_btn.setText(_translate("MainWindow", "Flip Card"))
        self.next_card_btn.setText(_translate("MainWindow", "Next Card"))
        self.chapter_label.setText(_translate("MainWindow", "Chapter"))
        self.objective_label.setText(_translate("MainWindow", "Objective"))
        self.section_label.setText(_translate("MainWindow", "Section"))
        self.update_deck_btn.setText(_translate("MainWindow", "Update Deck"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
